spring.application.name=MinhaAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/minhaapi
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true